# docker-compose.yml
version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    restart: always
    environment:
      # Environment variables are available https://github.com/itzg/docker-minecraft-server#server-configuration
      # Variables defined here are only applied the first time the container is built unless OVERRIDE_SERVER_PROPERTIES
      # is set to TRUE. Changes will be written to servers.properties on your MC server instance.
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ONLINE_MODE: "FALSE"

      SERVER_NAME: "Our Minecraft Server"
      MOTD: "Please play responsibly."
      
      DIFFICULTY: "normal"
      MODE: "creative"

      # # Allow attach to container and minecraft server console interactive
      # # bypasses graceful shutdown during docker stop. If that means something to you, then comment out.
      EXEC_DIRECTLY: "TRUE"

      # By default the vanilla log file will grow without limit. 
      ENABLE_ROLLING_LOGS: "TRUE"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 1500M

      # uncomment this to import a saved game. (put your savegame directory in the saves-to-import directory)
      # WORLD: "/worlds/My-World"

    #
    volumes:
      - ./minecraft-data:/data
      - ./saves-to-import:/worlds:ro